import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerWithBack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 10,
  },
  backBtn: {
    padding: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
  },
  homeBtn: {
    padding: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E293B',
  },
  infoCard: {
    backgroundColor: '#fff',
    margin: 20,
    padding: 25,
    borderRadius: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    marginBottom: 25,
  },
  statusLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  label: {
    fontSize: 10,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1,
  },
  connectingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
    gap: 2,
  },
  smallSpinner: {
    transform: [{ scale: 0.6 }],
  },
  connectingText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#F59E0B',
    textTransform: 'uppercase',
  },
  onlineBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
    gap: 4,
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
  },
  onlineText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#10B981',
    textTransform: 'uppercase',
  },
  offlineBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
    gap: 4,
  },
  offlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
  },
  offlineText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#EF4444',
    textTransform: 'uppercase',
  },
  infoText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1E293B',
  },
  scanBtn: {
    backgroundColor: '#0984e3',
    padding: 18,
    borderRadius: 18,
    alignItems: 'center',
  },
  scanBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  communicationBtn: {
    backgroundColor: '#10B981',
    marginHorizontal: 60,
    marginTop: 10,
    marginBottom: 10,
    padding: 18,
    borderRadius: 18,
    elevation: 3,
  },
  communicationBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  communicationBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  disconnectBtn: {
    marginTop: 12,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: '#EF4444',
  },
  disconnectBtnText: {
    color: '#F1F5F9',
    fontWeight: '800',
  },
});

export default styles;
